name: PR Comment CI

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  trigger-tests:
    if: ${{ github.event.issue.pull_request && (contains(github.event.comment.body, '/bot tests') || contains(github.event.comment.body, '/bot integration tests')) }}
    runs-on: ubuntu-latest
    steps:
      - name: Get PR details
        id: get-pr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'rocket'
            });

  test:
    runs-on: ubuntu-latest
    needs: trigger-tests

    steps:
    - name: Run test
      run: |
        echo "Test succeeds"

