name: PR Comment CI

on:
  issue_comment:
    types: [created]

permissions:
  statuses: write
  issues: write
  pull-requests: write
  contents: read

jobs:
  trigger-tests:
    if: ${{ github.event.issue.pull_request && (contains(github.event.comment.body, '/bot tests') || contains(github.event.comment.body, '/bot integration tests')) }}
    runs-on: ubuntu-latest
    steps:
      - name: Get PR details
        id: get-pr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'rocket'
            });

  test:
    runs-on: ubuntu-latest
    needs: trigger-tests
    steps:
      - name: Get PR details
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            core.setOutput('head_ref', pr.head.ref);
            core.setOutput('head_sha', pr.head.sha);
            core.setOutput('base_ref', pr.base.ref);
            
            return pr;

      - name: Create check run
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const { data: check } = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Integration Tests',
              head_sha: '${{ steps.pr.outputs.head_sha }}',
              status: 'in_progress',
              started_at: new Date().toISOString(),
              output: {
                title: 'Integration Tests',
                summary: 'Running integration tests...'
              }
            });
            
            core.setOutput('check_id', check.id);
            return check;
      
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.pr.outputs.head_ref }}

      - name: Run test
        run: |
          echo "Test succeeds"
      
      - name: Update check run
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const conclusion = '${{ job.status }}' === 'success' ? 'success' : 'failure';
            
            await github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: ${{ steps.check.outputs.check_id }},
              status: 'completed',
              conclusion: conclusion,
              completed_at: new Date().toISOString(),
              output: {
                title: `Integration Tests ${conclusion}`,
                summary: `The integration tests have ${conclusion === 'success' ? 'passed' : 'failed'}.`,
                text: 'Triggered by comment from @${{ github.actor }}'
              }
            });

